# Generated by Django 5.2.11 on 2026-02-17 22:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(db_index=True, help_text="Product name can't be blank or null has a max length of 120", max_length=120, verbose_name='Product name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price , decimal number , must be greater then 1 ', max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=1, message='The price must be greater then 1')], verbose_name='Product price')),
                ('description', models.TextField(blank=True, help_text='Product description, can be blank or null', null=True, verbose_name='Product description')),
                ('quantity', models.IntegerField(default=0, help_text='Product quantity in stock , integer , min : 0 ', validators=[django.core.validators.MinValueValidator(limit_value=0, message="product quantity can't be less then 0")], verbose_name='Product quantity in stock')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['created_at'],
            },
        ),
    ]
